[package]
name = "dotrix-explore"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotrix = { git = "https://github.com/lostinspiration/dotrix.git", branch="main" }